/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Railway;

import javax.swing.JFrame;

/**
 *
 * @author Rahul Vijayan
 */
public class Admin_Panel extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Panel
     */
    public Admin_Panel() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserReservationButton = new javax.swing.JButton();
        TrainDataButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        GoBackButton = new javax.swing.JButton();
        AdminPanel = new javax.swing.JPanel();
        AdminPanelLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        UserReservationButton.setBackground(new java.awt.Color(255, 153, 204));
        UserReservationButton.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        UserReservationButton.setText("User Reservation");
        UserReservationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserReservationButtonActionPerformed(evt);
            }
        });
        getContentPane().add(UserReservationButton);
        UserReservationButton.setBounds(390, 220, 320, 150);

        TrainDataButton.setBackground(new java.awt.Color(255, 153, 204));
        TrainDataButton.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        TrainDataButton.setText("Train Data");
        TrainDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrainDataButtonActionPerformed(evt);
            }
        });
        getContentPane().add(TrainDataButton);
        TrainDataButton.setBounds(790, 220, 310, 150);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abhishek\\Documents\\NetBeansProjects\\Railway Reservation System\\images\\rails-e1517953223560-1024x573.jpeg")); // NOI18N
        jLabel1.setText("j");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-1470, 630, 2670, 1190);

        GoBackButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        GoBackButton.setText("Back");
        GoBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GoBackButtonMouseClicked(evt);
            }
        });
        GoBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(GoBackButton);
        GoBackButton.setBounds(710, 400, 80, 40);

        AdminPanel.setBackground(new java.awt.Color(6, 51, 51));
        AdminPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        AdminPanelLabel.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        AdminPanelLabel.setForeground(new java.awt.Color(255, 255, 51));
        AdminPanelLabel.setText("Admin Panel");

        javax.swing.GroupLayout AdminPanelLayout = new javax.swing.GroupLayout(AdminPanel);
        AdminPanel.setLayout(AdminPanelLayout);
        AdminPanelLayout.setHorizontalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPanelLayout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(AdminPanelLabel)
                .addContainerGap(231, Short.MAX_VALUE))
        );
        AdminPanelLayout.setVerticalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(AdminPanelLabel)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(AdminPanel);
        AdminPanel.setBounds(390, 40, 710, 90);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TrainDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrainDataButtonActionPerformed
        // TODO add your handling code here:
        
        Train_Details t = new Train_Details();
        t.setLocationRelativeTo(null);
        t.setVisible(true);
        
        
    }//GEN-LAST:event_TrainDataButtonActionPerformed

    private void UserReservationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserReservationButtonActionPerformed
        // TODO add your handling code here:
        
        UserData u = new UserData();
        u.setLocationRelativeTo(null);
        u.setVisible(true);
        
    }//GEN-LAST:event_UserReservationButtonActionPerformed

    private void GoBackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoBackButtonMouseClicked
        // TODO add your handling code here:
        Home h = new Home();
        h.setLocationRelativeTo(null);
        h.setVisible(true);
    }//GEN-LAST:event_GoBackButtonMouseClicked

    private void GoBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBackButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GoBackButtonActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        Home h = new Home();
        h.setLocationRelativeTo(null);
        h.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminPanel;
    private javax.swing.JLabel AdminPanelLabel;
    private javax.swing.JButton GoBackButton;
    private javax.swing.JButton TrainDataButton;
    private javax.swing.JButton UserReservationButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
