/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Railway;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Random;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rahul Vijayan
 */
public class Train_Details extends javax.swing.JFrame {

    /**
     * Creates new form Train_Details
     */
    public Train_Details() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        Connect();
        //trainidgenerator();
        trainno();
        train_detail();
    }
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    public void Connect()
    {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/railway_reservation_system","root","Abhi");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Train_Details.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Train_Details.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }
    
    public void trainidgenerator()
    {
        Random r=new Random();
        int n=r.nextInt(50000000)+1;
        String val=String.valueOf(n);
        trainid.setText(val);
    }
    
    public void trainno()
    {
        try{
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select MAX(trainId) from train");
            rs.next();
            rs.getString("MAX(trainId)");
            
            if(rs.getString("MAX(trainId)")== null)
            {
                trainid.setText("T-0000001");
            }
            else{
                long id=Long.parseLong(rs.getString("MAX(trainId)").substring(2,rs.getString("MAX(trainId)").length()));
                id++;
                trainid.setText("T-"+String.format("%07d", id));
            }
        }catch(SQLException ex){
            Logger.getLogger(Train_Details.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void train_detail()
    {
        
        try {
            pst=con.prepareStatement("select * from train");
            rs=pst.executeQuery();
            
            ResultSetMetaData rsd = rs.getMetaData();
            int c;
            c=rsd.getColumnCount();
            DefaultTableModel d = (DefaultTableModel)TrainDetailsTable.getModel();
            d.setRowCount(0);
            
            while(rs.next())
            {
                Vector v = new Vector();
                for(int i=0;i<=c;i++)
                {
                    v.add(rs.getString("trainId"));
                    v.add(rs.getString("trainName"));
                    v.add(rs.getString("startPlace"));
                    v.add(rs.getString("destinationPlace"));
                    v.add(rs.getString("seatType"));
                    v.add(rs.getString("Price"));
                }
                
                d.addRow(v);
            }
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Train_Details.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TrainDetailsPanel = new javax.swing.JPanel();
        TrainDetailsLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TrainDetailsTable = new javax.swing.JTable();
        TrainIDLabel = new javax.swing.JLabel();
        TrainNameLabel = new javax.swing.JLabel();
        StartPlaceLabel = new javax.swing.JLabel();
        DestinationPlaceLabel = new javax.swing.JLabel();
        PriceLabel = new javax.swing.JLabel();
        tname = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        price = new javax.swing.JTextField();
        splace = new javax.swing.JTextField();
        dplace = new javax.swing.JTextField();
        tname1 = new javax.swing.JTextField();
        ResetButton = new javax.swing.JButton();
        GoBackButton = new javax.swing.JButton();
        SeatTypeLabel = new javax.swing.JLabel();
        seatType = new javax.swing.JComboBox<>();
        trainid = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        TrainDetailsPanel.setBackground(new java.awt.Color(255, 204, 255));
        TrainDetailsPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TrainDetailsLabel.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        TrainDetailsLabel.setForeground(new java.awt.Color(0, 102, 255));
        TrainDetailsLabel.setText("Train Details");

        javax.swing.GroupLayout TrainDetailsPanelLayout = new javax.swing.GroupLayout(TrainDetailsPanel);
        TrainDetailsPanel.setLayout(TrainDetailsPanelLayout);
        TrainDetailsPanelLayout.setHorizontalGroup(
            TrainDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TrainDetailsPanelLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(TrainDetailsLabel)
                .addContainerGap(161, Short.MAX_VALUE))
        );
        TrainDetailsPanelLayout.setVerticalGroup(
            TrainDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TrainDetailsPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(TrainDetailsLabel)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(TrainDetailsPanel);
        TrainDetailsPanel.setBounds(440, 30, 590, 90);

        TrainDetailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TrainID", "Train Name", "Start Place", "Destination Place", "Seat Type", "Price"
            }
        ));
        TrainDetailsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TrainDetailsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TrainDetailsTable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(630, 140, 720, 402);

        TrainIDLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        TrainIDLabel.setForeground(new java.awt.Color(255, 0, 0));
        TrainIDLabel.setText("Train ID:");
        getContentPane().add(TrainIDLabel);
        TrainIDLabel.setBounds(210, 200, 110, 20);

        TrainNameLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        TrainNameLabel.setForeground(new java.awt.Color(255, 0, 0));
        TrainNameLabel.setText("Train Name:");
        getContentPane().add(TrainNameLabel);
        TrainNameLabel.setBounds(210, 250, 140, 29);

        StartPlaceLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        StartPlaceLabel.setForeground(new java.awt.Color(255, 0, 0));
        StartPlaceLabel.setText("Start Place:");
        getContentPane().add(StartPlaceLabel);
        StartPlaceLabel.setBounds(210, 310, 140, 20);

        DestinationPlaceLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        DestinationPlaceLabel.setForeground(new java.awt.Color(255, 0, 0));
        DestinationPlaceLabel.setText("Destination Place:");
        getContentPane().add(DestinationPlaceLabel);
        DestinationPlaceLabel.setBounds(210, 350, 190, 30);

        PriceLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        PriceLabel.setForeground(new java.awt.Color(255, 0, 0));
        PriceLabel.setText("Price:");
        getContentPane().add(PriceLabel);
        PriceLabel.setBounds(210, 450, 90, 30);
        getContentPane().add(tname);
        tname.setBounds(430, 250, 150, 30);

        AddButton.setBackground(new java.awt.Color(51, 51, 0));
        AddButton.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        AddButton.setForeground(new java.awt.Color(255, 255, 255));
        AddButton.setText("ADD");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AddButton);
        AddButton.setBounds(210, 590, 90, 40);

        UpdateButton.setBackground(new java.awt.Color(51, 51, 0));
        UpdateButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        UpdateButton.setForeground(new java.awt.Color(255, 255, 255));
        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateButton);
        UpdateButton.setBounds(320, 590, 130, 40);

        DeleteButton.setBackground(new java.awt.Color(51, 51, 0));
        DeleteButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        DeleteButton.setForeground(new java.awt.Color(255, 255, 255));
        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteButton);
        DeleteButton.setBounds(470, 590, 110, 40);
        getContentPane().add(price);
        price.setBounds(430, 450, 150, 30);
        getContentPane().add(splace);
        splace.setBounds(430, 300, 150, 30);
        getContentPane().add(dplace);
        dplace.setBounds(430, 350, 150, 30);
        getContentPane().add(tname1);
        tname1.setBounds(430, 250, 150, 30);

        ResetButton.setBackground(new java.awt.Color(51, 51, 0));
        ResetButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        ResetButton.setForeground(new java.awt.Color(255, 255, 255));
        ResetButton.setText("Reset");
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ResetButton);
        ResetButton.setBounds(600, 590, 100, 39);

        GoBackButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        GoBackButton.setText("Back");
        GoBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GoBackButtonMouseClicked(evt);
            }
        });
        GoBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(GoBackButton);
        GoBackButton.setBounds(720, 590, 80, 40);

        SeatTypeLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        SeatTypeLabel.setForeground(new java.awt.Color(255, 0, 0));
        SeatTypeLabel.setText("Seat Type:");
        getContentPane().add(SeatTypeLabel);
        SeatTypeLabel.setBounds(210, 400, 200, 30);

        seatType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1A", "2A", "3A", "SL" }));
        seatType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatTypeActionPerformed(evt);
            }
        });
        getContentPane().add(seatType);
        seatType.setBounds(430, 400, 150, 30);

        trainid.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        trainid.setForeground(new java.awt.Color(51, 51, 255));
        getContentPane().add(trainid);
        trainid.setBounds(450, 190, 150, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
        
        String ID = trainid.getText();
        String TrainName = tname.getText();
        String StartPlace = splace.getText();
        String DestinationPlace = dplace.getText();
        String SeatType=seatType.getSelectedItem().toString();
        String Price = price.getText();
        
        try {
            pst = con.prepareStatement("insert into train(trainId,trainName,startPlace,destinationPlace,seatType,Price)values(?,?,?,?,?,?)");
            
            pst.setString(1, ID);
            pst.setString(2, TrainName);
            pst.setString(3, StartPlace);
            pst.setString(4, DestinationPlace);
            pst.setString(5, SeatType);
            pst.setString(6, Price);
            
            int k = pst.executeUpdate();
            
            if(k==1)
            {
                JOptionPane.showMessageDialog(this, "Record Added Successfully");
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Record Adding Failed");
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Train_Details.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_AddButtonActionPerformed

    private void TrainDetailsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrainDetailsTableMouseClicked
        // TODO add your handling code here:
        
        
        DefaultTableModel d = (DefaultTableModel)TrainDetailsTable.getModel();
        
        int selectIndex = TrainDetailsTable.getSelectedRow();
        
        trainid.setText(d.getValueAt(selectIndex, 0).toString());
        tname.setText(d.getValueAt(selectIndex, 1).toString());
        splace.setText(d.getValueAt(selectIndex, 2).toString());
        dplace.setText(d.getValueAt(selectIndex, 3).toString());
        seatType.setSelectedItem(d.getValueAt(selectIndex, 4).toString());
        price.setText(d.getValueAt(selectIndex, 5).toString());
        
        AddButton.setEnabled(false);
    }//GEN-LAST:event_TrainDetailsTableMouseClicked

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
        
        String tID = trainid.getText();
        String TrainName = tname.getText();
        String StartPlace = splace.getText();
        String DestinationPlace = dplace.getText();
        String SeatType=seatType.getSelectedItem().toString();
        String Price = price.getText();
        
        try {
            pst = con.prepareStatement("update train set trainName=?, startPlace=?, destinationPlace=?,seatType=?, Price=? where trainId=?");
            
           
            pst.setString(1, TrainName);
            pst.setString(2, StartPlace);
            pst.setString(3, DestinationPlace);
            pst.setString(4, SeatType);
            pst.setString(5, Price);
            pst.setString(6, tID);
            
            int k = pst.executeUpdate();
            
            if(k==1)
            {
                JOptionPane.showMessageDialog(this, "Record Updated Successfully");
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Record Updation Failed");
            }
            
            trainid.setText("");
            tname.setText("");
            splace.setText("");
            dplace.setText("");
            seatType.getSelectedItem().toString();
            //ticket.setText("");
            price.setText("");
            trainid.requestFocus();
            train_detail();
            AddButton.setEnabled(true);
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Train_Details.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
        
        String ID = trainid.getText();
        
        try {
            pst = con.prepareStatement("delete from train where trainId=?");
            
            pst.setString(1, ID);
            
            
            int k = pst.executeUpdate();
            
            if(k==1)
            {
                JOptionPane.showMessageDialog(this, "Record Deleted Successfully");
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Record Deletion Failed");
            }
            
            trainid.setText("");
            tname.setText("");
            splace.setText("");
            dplace.setText("");
            seatType.getSelectedItem().toString();
            price.setText("");
            trainid.requestFocus();
            train_detail();
            AddButton.setEnabled(true);
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Train_Details.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
        // TODO add your handling code here:
        
        train_detail();
        AddButton.setEnabled(true);
        
    }//GEN-LAST:event_ResetButtonActionPerformed

    private void GoBackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoBackButtonMouseClicked
        // TODO add your handling code here:
        Admin_Panel ap = new Admin_Panel();
        ap.setLocationRelativeTo(null);
        ap.setVisible(true);
    }//GEN-LAST:event_GoBackButtonMouseClicked

    private void GoBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBackButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GoBackButtonActionPerformed

    private void seatTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatTypeActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_seatTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Train_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Train_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Train_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Train_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Train_Details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JLabel DestinationPlaceLabel;
    private javax.swing.JButton GoBackButton;
    private javax.swing.JLabel PriceLabel;
    private javax.swing.JButton ResetButton;
    private javax.swing.JLabel SeatTypeLabel;
    private javax.swing.JLabel StartPlaceLabel;
    private javax.swing.JLabel TrainDetailsLabel;
    private javax.swing.JPanel TrainDetailsPanel;
    private javax.swing.JTable TrainDetailsTable;
    private javax.swing.JLabel TrainIDLabel;
    private javax.swing.JLabel TrainNameLabel;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JTextField dplace;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField price;
    private javax.swing.JComboBox<String> seatType;
    private javax.swing.JTextField splace;
    private javax.swing.JTextField tname;
    private javax.swing.JTextField tname1;
    private javax.swing.JLabel trainid;
    // End of variables declaration//GEN-END:variables
}
