/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Railway;

import com.sun.org.apache.bcel.internal.generic.Select;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Random;
import java.util.jar.Attributes.Name;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Rahul Vijayan
 */
public class User_Signup extends javax.swing.JFrame {

    /**
     * Creates new form User_Signup
     */
    public User_Signup() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        Connect();
        UserID();
       //id_autoincreament();
        
    }
    
    
    Connection con;
    PreparedStatement pst;
   
    
    private String generateBookingID() {
        // Generate a unique room ID using UUID
        Random random = new Random();
        int bookingIdNumber = 10000 + random.nextInt(90000); // Generate a n-digit random number
        return String.valueOf(bookingIdNumber);
    }
    
    private void id_autoincreament(){
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/railway_reservation_system","root","Abhi");
            Statement s=con.createStatement();
            String sqlquery="select userId from user";
            PreparedStatement pst=con.prepareStatement(sqlquery);
            ResultSet rs=pst.executeQuery();
            if(rs.next()){
                int id1=rs.getInt(10);
                int n=id1+1;
                userid.setText(Integer.toString(n));
                
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        
    }
    public void Connect()
    {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/railway_reservation_system","root","Abhi");
            Statement s=con.createStatement();
            //con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql?zeroDateTimeBehavior=CONVERT_TO_NULL","root","Abhi");
            
            ResultSet rs=s.executeQuery("select userId from user");
            rs.next();
            
           
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(User_Signup.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(User_Signup.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void UserID()
    {
        try{
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select MAX(userId) from user");
            rs.next();
            rs.getString("MAX(userId)");
            
            if(rs.getString("MAX(userId)")== null)
            {
                userid.setText("U-1");
            }
            else{
                long id=Long.parseLong(rs.getString("MAX(userId)").substring(2,rs.getString("MAX(userId)").length()));
                id++;
                userid.setText("U-"+String.format("%d", id));
            }
        }catch(SQLException ex){
            Logger.getLogger(Train_Details.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        UserIDLabel = new javax.swing.JLabel();
        UsernameLabel = new javax.swing.JLabel();
        PhoneNoLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        passw = new javax.swing.JPasswordField();
        RegisterButton = new javax.swing.JButton();
        UserSignupPanel = new javax.swing.JPanel();
        UserSignupLabel = new javax.swing.JLabel();
        SignInLabel = new javax.swing.JLabel();
        GoBackButton = new javax.swing.JButton();
        userid = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        UserIDLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        UserIDLabel.setForeground(new java.awt.Color(255, 0, 0));
        UserIDLabel.setText("User ID:");
        getContentPane().add(UserIDLabel);
        UserIDLabel.setBounds(490, 150, 90, 40);

        UsernameLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        UsernameLabel.setForeground(new java.awt.Color(255, 0, 0));
        UsernameLabel.setText("Username:");
        getContentPane().add(UsernameLabel);
        UsernameLabel.setBounds(490, 210, 120, 30);

        PhoneNoLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        PhoneNoLabel.setForeground(new java.awt.Color(255, 0, 0));
        PhoneNoLabel.setText("Phone No:");
        getContentPane().add(PhoneNoLabel);
        PhoneNoLabel.setBounds(490, 330, 120, 40);

        EmailLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        EmailLabel.setForeground(new java.awt.Color(255, 0, 0));
        EmailLabel.setText("Email:");
        getContentPane().add(EmailLabel);
        EmailLabel.setBounds(490, 270, 80, 30);

        PasswordLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        PasswordLabel.setForeground(new java.awt.Color(255, 0, 0));
        PasswordLabel.setText("Password:");
        getContentPane().add(PasswordLabel);
        PasswordLabel.setBounds(490, 380, 120, 40);
        getContentPane().add(username);
        username.setBounds(630, 210, 220, 30);

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email);
        email.setBounds(630, 270, 220, 30);
        getContentPane().add(phone);
        phone.setBounds(630, 330, 220, 30);
        getContentPane().add(passw);
        passw.setBounds(630, 390, 220, 30);

        RegisterButton.setBackground(new java.awt.Color(51, 51, 0));
        RegisterButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        RegisterButton.setForeground(new java.awt.Color(255, 255, 255));
        RegisterButton.setText("Register");
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });
        getContentPane().add(RegisterButton);
        RegisterButton.setBounds(630, 440, 130, 40);

        UserSignupPanel.setBackground(new java.awt.Color(0, 51, 51));
        UserSignupPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        UserSignupLabel.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        UserSignupLabel.setForeground(new java.awt.Color(255, 255, 51));
        UserSignupLabel.setText("User SignUp");

        javax.swing.GroupLayout UserSignupPanelLayout = new javax.swing.GroupLayout(UserSignupPanel);
        UserSignupPanel.setLayout(UserSignupPanelLayout);
        UserSignupPanelLayout.setHorizontalGroup(
            UserSignupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserSignupPanelLayout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(UserSignupLabel)
                .addContainerGap(150, Short.MAX_VALUE))
        );
        UserSignupPanelLayout.setVerticalGroup(
            UserSignupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserSignupPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(UserSignupLabel)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(UserSignupPanel);
        UserSignupPanel.setBounds(400, 20, 560, 95);

        SignInLabel.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        SignInLabel.setForeground(new java.awt.Color(0, 51, 255));
        SignInLabel.setText("Already a User? Click here to SignIn");
        SignInLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignInLabelMouseClicked(evt);
            }
        });
        getContentPane().add(SignInLabel);
        SignInLabel.setBounds(610, 500, 400, 40);

        GoBackButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        GoBackButton.setText("Back");
        GoBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GoBackButtonMouseClicked(evt);
            }
        });
        GoBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(GoBackButton);
        GoBackButton.setBounds(770, 440, 80, 40);

        userid.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        userid.setForeground(new java.awt.Color(51, 0, 255));
        getContentPane().add(userid);
        userid.setBounds(650, 150, 180, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void SignInLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignInLabelMouseClicked
        // TODO add your handling code here:
        
        User_Signin u = new User_Signin();
        u.setLocationRelativeTo(null);
        u.setVisible(true);
        this.hide();
    }//GEN-LAST:event_SignInLabelMouseClicked

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        // TODO add your handling code here:
        
        String ID = userid.getText();
        String Username = username.getText();
        String Email = email.getText();
        String Phone = phone.getText();
        String Pass = passw.getText();
        
        
        try {
            pst = con.prepareStatement("insert into user(userId,username,email,phone,password)values(?,?,?,?,?)");
            
            pst.setString(1, ID);
            pst.setString(2, Username);
            pst.setString(3, Email);
            pst.setString(4, Phone);
            pst.setString(5, Pass);
            //id_autoincreament();
            
            int k = pst.executeUpdate();
            
            if(k==1)
            {
                JOptionPane.showMessageDialog(this, "Record Added Successfully!!!...Please Remember your Username and Password");
            }
            
                    
                    } catch (SQLException ex) {
            Logger.getLogger(User_Signup.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void GoBackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoBackButtonMouseClicked
        // TODO add your handling code here:
        User_Signin u = new User_Signin();
        u.setLocationRelativeTo(null);
        u.setVisible(true);
    }//GEN-LAST:event_GoBackButtonMouseClicked

    private void GoBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBackButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GoBackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JButton GoBackButton;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JLabel PhoneNoLabel;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JLabel SignInLabel;
    private javax.swing.JLabel UserIDLabel;
    private javax.swing.JLabel UserSignupLabel;
    private javax.swing.JPanel UserSignupPanel;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField passw;
    private javax.swing.JTextField phone;
    private javax.swing.JLabel userid;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
