/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Railway;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Rahul Vijayan
 */
public class User_Signin extends javax.swing.JFrame {

    /**
     * Creates new form User_Signin
     */
    public User_Signin() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        Connect();
    }
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    public void Connect()
    {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/railway_reservation_system","root","Abhi");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(User_Signup.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(User_Signup.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        UserLoginPanel = new javax.swing.JPanel();
        UserLoginLabel = new javax.swing.JLabel();
        UsernameLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        SubmitButton = new javax.swing.JButton();
        NewUserLabel = new javax.swing.JLabel();
        GoBackButton = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        UserLoginPanel.setBackground(new java.awt.Color(0, 51, 51));

        UserLoginLabel.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        UserLoginLabel.setForeground(new java.awt.Color(255, 255, 51));
        UserLoginLabel.setText("User Login");

        javax.swing.GroupLayout UserLoginPanelLayout = new javax.swing.GroupLayout(UserLoginPanel);
        UserLoginPanel.setLayout(UserLoginPanelLayout);
        UserLoginPanelLayout.setHorizontalGroup(
            UserLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserLoginPanelLayout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(UserLoginLabel)
                .addContainerGap(187, Short.MAX_VALUE))
        );
        UserLoginPanelLayout.setVerticalGroup(
            UserLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserLoginPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(UserLoginLabel)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(UserLoginPanel);
        UserLoginPanel.setBounds(360, 30, 570, 90);

        UsernameLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        UsernameLabel.setForeground(new java.awt.Color(255, 0, 0));
        UsernameLabel.setText("Username:");
        getContentPane().add(UsernameLabel);
        UsernameLabel.setBounds(430, 180, 130, 40);

        PasswordLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        PasswordLabel.setForeground(new java.awt.Color(255, 0, 0));
        PasswordLabel.setText("Password:");
        getContentPane().add(PasswordLabel);
        PasswordLabel.setBounds(430, 250, 120, 30);
        getContentPane().add(user);
        user.setBounds(580, 190, 270, 30);
        getContentPane().add(pass);
        pass.setBounds(580, 250, 270, 30);

        SubmitButton.setBackground(new java.awt.Color(51, 51, 0));
        SubmitButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        SubmitButton.setForeground(new java.awt.Color(255, 255, 255));
        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SubmitButton);
        SubmitButton.setBounds(580, 310, 120, 40);

        NewUserLabel.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        NewUserLabel.setForeground(new java.awt.Color(255, 0, 51));
        NewUserLabel.setText("New User? Click here to SignUp");
        NewUserLabel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                NewUserLabelAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        NewUserLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewUserLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NewUserLabelMouseEntered(evt);
            }
        });
        getContentPane().add(NewUserLabel);
        NewUserLabel.setBounds(580, 360, 350, 40);

        GoBackButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        GoBackButton.setText("Back");
        GoBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GoBackButtonMouseClicked(evt);
            }
        });
        GoBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(GoBackButton);
        GoBackButton.setBounds(770, 310, 80, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        try {
            // TODO add your handling code here:
            
            String Username = user.getText();
            String Password = pass.getText();
            String sql = "select * from user where username=? and password=?";
            pst=con.prepareStatement(sql);
            pst.setString(1, Username);
            pst.setString(2, Password);
            rs=pst.executeQuery();
            if(rs.next())
            {
                JOptionPane.showMessageDialog(this, "Signin Successfully");
                Reservation r = new Reservation();
                r.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Signin Failed");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(User_Signin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void NewUserLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewUserLabelMouseEntered
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_NewUserLabelMouseEntered

    private void NewUserLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewUserLabelMouseClicked
        // TODO add your handling code here:
        
        User_Signup u = new User_Signup();
        u.setLocationRelativeTo(null);
        u.setVisible(true);
        
        
    }//GEN-LAST:event_NewUserLabelMouseClicked

    private void NewUserLabelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_NewUserLabelAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_NewUserLabelAncestorAdded

    private void GoBackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoBackButtonMouseClicked
        // TODO add your handling code here:
        Home h = new Home();
        h.setLocationRelativeTo(null);
        h.setVisible(true);
    }//GEN-LAST:event_GoBackButtonMouseClicked

    private void GoBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBackButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GoBackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_Signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_Signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_Signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_Signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_Signin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GoBackButton;
    private javax.swing.JLabel NewUserLabel;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JLabel UserLoginLabel;
    private javax.swing.JPanel UserLoginPanel;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
